Feature 156 UI cleanup and components
Metatavu/megasense-mobile pull request #160
Opened 2021-06-09 07:48 UTC by Kaemppi

Resolves #156

2021-06-09 12:43 UTC, Daniilmass requested changes
Are there any benefits in using the react functional components in this application? Just curious.

2021-06-09 12:43 UTC, Daniilmass commented on src/components/layout/app-layout.tsx
> +import React from "react";
What is the reason for using react functional component here?

2021-06-10 07:41 UTC, Kaemppi commented on src/components/generic/progress-bar-accordion.tsx
> +  const [ open, setOpen ] = useState(false);
The company code style seems to encourage to use it such way to help readability.

2021-06-10 07:48 UTC, Daniilmass commented on src/components/generic/progress-bar-accordion.tsx
> +  const [ open, setOpen ] = useState(false);
Oh! I thought it applies to { ... } not the [ ... ]

2021-06-10 07:56 UTC, Kaemppi commented on src/components/generic/rounded-button.tsx
> +    } = this.props;
I have used it when it goes over two to increase readability

2021-06-10 13:12 UTC, Kaemppi commented on src/components/layout/app-layout.tsx
> +import React from "react";
We have preferred using the functional format in simple components. Functionals are also pretty useful in general.

2021-06-10 13:14 UTC, merged