Feature 210 colored route
Metatavu/megasense-mobile pull request #213
Opened 2021-12-14 13:37 UTC by Chi-Chu319

resolves #210

2021-12-15 14:00 UTC, Daniilmass commented on src/localization/fi.json
> +    "listAirQuality": "Error when listing air quality",
Should be in finnish
@Kaemppi Could you help?

2021-12-15 14:11 UTC, Daniilmass requested changes

2021-12-15 14:11 UTC, Daniilmass commented on src/utils/routing-utils.tsx
> +  public static stokeColorConverter = (pollutants: Pollutant[], routeAirQuality: AirQuality[], baseColor: string) =>{
Please add the TSdocs

2021-12-15 14:11 UTC, Daniilmass commented on src/utils/routing-utils.tsx
> +  public static getPollutantColorFaction = (baseColor: string, fraction: number): string => {
Please remove non-existing params from TSdocs

2021-12-15 14:11 UTC, Daniilmass commented on src/components/screens/main-screen.tsx
> +   * @returns modified route line
```suggestion
   * Creates a route offset
   * 
   * @param routeAlts the route alternatives
   * @returns modified route lines
```
Should it be like that?

2021-12-15 14:22 UTC, Chi-Chu319 commented on src/localization/fi.json
> +    "listAirQuality": "Error when listing air quality",
Totally missed this part...

2021-12-16 09:35 UTC, Kaemppi commented on src/localization/fi.json
> +    "listAirQuality": "Error when listing air quality",
```suggestion
    "listRoutingModes": "Virhe reittityyppien listaamisessa",
    "listPollutant": "Virhe saasteiden listaamisessa.",
    "fetchRouteLine": "Virhe reitin hakemisessa",
    "listAirQuality": "Virhe ilmanlaadun listauksessa",
```

2021-12-16 09:40 UTC, merged